### ISSUE TITLE
Source of your theme?

### ISSUE THREAD

**Issue by miqbal23** [NickCraver/nickcraver.github.com#15]
I'm currently trying various Jekyll themes for my blog at GitHub. May I know where did you get yours, or did you build it yourself?

**Comment by NickCraver** [comment]
Just built it myself, with some awesome tweaking advice from Jin Yang. I blogged about it here: https://nickcraver.com/blog/2015/03/24/optimization-considerations/

**Comment by miqbal23** [comment]
Thank you, I'll consider trying your theme on mine (I'll also put reference to your site for copyright)

Also, please send my regard to Jin Yang. He had done simple, yet awesome design on your blog
