### ISSUE TITLE
Reuse of the style

### ISSUE THREAD

**Issue by Kmaschta** [NickCraver/nickcraver.github.com#23]
Hi there,

Your Jekyll style is really cool, simple, suitable and I enjoy to read your awesome posts with it!

I consider to create an personal website since a while but the style freeze me.
May I ask you if your style is a piece of your work and if yes, can I reuse it partially or most of it?

**Comment by NickCraver** [comment]
Thanks! And go nuts, feel free to use any styling you want :)

**Comment by Kmaschta** [comment]
I credited you for the style on [my new website](https://www.kmaschta.me/), let me know if I can do anything.

Thank you!

**Comment by NickCraver** [comment]
Thanks for the link back, you're a stand up guy already even asking at all. <3

Closing this out just to cleanup, much appreciated sir.
