### ISSUE TITLE
HTTPS post missing read more link

### ISSUE THREAD

**Issue by mmillican** [NickCraver/nickcraver.github.com#32]
The [HTTPS post](https://github.com/NickCraver/nickcraver.github.com/blob/master/blog/_posts/2017-05-22-https-on-stack-overflow.markdown) is missing a `<!--more-->` tag so it's not being truncated.  Scrolling down the post list is _really_ long to get to previous posts.  

I'd submit a PR for it, but not sure the best place for it, so thought issue is the next best thing.  Let me know if you'd prefer a PR.

**Comment by NickCraver** [comment]
This is intentional. The most recent post is not collapsed, I collapse it when the next post goes live, that means users don't have to click through to read the full content when landing on the blog landing.

**Comment by mmillican** [comment]
Ahh gotcha.

**Comment by mmillican** [comment]
By the way, I only noticed this because I was looking for your hardware post - which is why i had to scroll way down.
