### ISSUE TITLE
How to generate SO-Architecture-Overview-Logical?

### ISSUE THREAD

**Issue by SamuelMarks** [NickCraver/nickcraver.github.com#34]
How did you generate [SO-Architecture-Overview-Logical.svg](https://raw.githubusercontent.com/NickCraver/nickcraver.github.com/master/blog/content/SO-Architecture-Overview-Logical.svg)?

<img src="https://raw.githubusercontent.com/NickCraver/nickcraver.github.com/master/blog/content/SO-Architecture-Overview-Logical.svg" alt="SO-Architecture-Overview-Logical.svg"/>

It looks quite nice, would be useful to show the architecture of all my open-source tech 😃

**Comment by NickCraver** [comment]
I am using https://www.draw.io/ for diagrams these days - highly recommend it!
