### ISSUE TITLE
Something strange is happening with Links in Markdown

### ISSUE THREAD

**Issue by dan-drews** [NickCraver/nickcraver.github.com#35]
In your blog at this url: https://nickcraver.com/blog/2016/02/17/stack-overflow-the-architecture-2016-edition/#load-balancers-haproxy
there are some issues happening with Markdown links. I'm not familiar enough with markdown to fix it, so I wanted to submit a ticket.

The headers with links like HAProxy and Elasticsearch are rendering headers as this:

Elasticsearch)Search (Elasticsearch)
or 
HAProxy)Load Balancers (HAProxy)

I'm assuming this is a bug, but if it's actually a feature, then we can close this up 😀 

UPDATE:
I forgot the link

**Comment by NickCraver** [comment]
Fixed in 2499bb5d918c952721a4dccfd484a66c00e151e0, thanks!!
