### ISSUE TITLE
OPServer : need .json files for my AD, DNS & Other servers...

### ISSUE THREAD

**Issue by Hsingh79** [NickCraver/nickcraver.github.com#5]
Hello,

I Installed & Configured OPServer for my SQL Server through "SQLSettings.json.example" file and It is working perfect. I am not from programming filed so I need help.
I need .json files like "SQLSettings.json.example". I want to add and Monitor my AD (windows active directory) server & DNS Server as well as other servers (File Server, Print Server, Web Serevr or a Normal Server) in my network.

Please Advise me ASAP !

Thanks & Regards,
Hariom Prakash Singh. Delhi, India

**Comment by NickCraver** [comment]
@Hsingh79 Opserver doesn't have monitoring for these things yet, though it's on my radar. If you want to pitch suggestions, please do so! The Opserver repo (and issues) are here: https://github.com/Opserver/Opserver
